### ISSUE TITLE
What is Joel's  script

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#26]
I am confused about this from the README.md instructions:

"If you are using Joel's script for binding instrument to /dev/radiometerX, you should be good, otherwise you should change in config_hypernets.ini the hypstar_port parameter to /dev/ttyUSBx (normally ttyUSB0)."

What is Joel's script? @jkuusk or @corizzi?

Thanks.

**Comment by jkuusk** [comment]
It is 04_configure_ports.sh in the install/ folder which sets up an udev rule for linking the ftdi usb-serial converter's device to /dev/radiometer0 so that the radiometer can always be accessed from the same device independent of the order of configuring the ttyUSB devices. The order of connecting the GSM modem and usb-serial converter depends on the physical USB port that is used for the ftdi board. If it is connected to the USB3 port, it seems to be configured before the GSM modem devices and is assigned the /dev/ttyUSB0 device. In all the USB2 ports the GSM modem is configured first and the ftdi chip is assigned the /dev/ttyUSB5 device.

**Comment by javierconcha** [comment]
Understood. Thanks!

I already had run 04_configure_ports.sh without knowing that was your script while trying to solve the issue that the radiometer is not taking measurements. Just to confirm, using this script, in the config file:
hypstar_port = /dev/radiometer0
Correct?

**Comment by jkuusk** [comment]
Yes, that should work. If not, you can also use /dev/ttyUSBx (probably /dev/ttyUSB5 which was hardcoded previously and seems to have worked for most of the systems).
