### ISSUE TITLE
Naming the webcams files with prefix

### ISSUE THREAD

**Issue by javierconcha** [HYPERNETS/hypernets_tools#39]
We would like to request an option to add a prefix to the webcam files:
From:
"$OUTPUT_DIR/$DATE.jpg"
to:
"$OUTPUT_DIR/$PREFIX_$DATE.jpg"

This would help to differentiate the files from the two webcams without the need to preserve the directory structure.

**Comment by corizzi** [comment]
9ee258a987c347333f75cda3b9a600d12fd799d2

Hi @javierconcha, I added "-p your_prefix" option. Could you test please ?

**Comment by vitbrando** [comment]
HI Alex,
it looks like this change messed up something else.
since 12 VEIT is not rsyncing with enhidra, as I jus reported on GLPI.

We get the same error every 15 minutes:

mag 19 12:15:42 hypernets-cnr1 systemd[1]: Started Hypernets Sync Config Server and Send Data.
mag 19 12:15:42 hypernets-cnr1 hello_server.sh[673]: Sleep 30 sec
mag 19 12:16:14 hypernets-cnr1 hello_server.sh[673]: Touching hypstar@enhydra.naturalsciences.be:/waterhypernet/HYPSTAR/Raw/VEIT//system_is_up
mag 19 12:16:15 hypernets-cnr1 hello_server.sh[673]: Sync files : hypstar@enhydra.naturalsciences.be:/waterhypernet/HYPSTAR/Raw/VEIT//config_hypernets.ini.hypernets
mag 19 12:16:15 hypernets-cnr1 hello_server.sh[673]:         <->  config_hypernets.ini
mag 19 12:16:16 hypernets-cnr1 hello_server.sh[673]: Files are synchronized.
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[931]: From https://github.com/HYPERNETS/hypernets_tools
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[931]:    bda2939..9ee258a  VEIT       -> origin/VEIT
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[939]: error: Your local changes to the following files would be overwritten by merge:
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[939]:         webcamGetImg.sh
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[939]: Please commit your changes or stash them before you merge.
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[939]: Aborting
mag 19 12:16:17 hypernets-cnr1 hello_server.sh[939]: Updating bda2939..9ee258a
mag 19 12:16:17 hypernets-cnr1 systemd[1]: hypernets-hello.service: Main process exited, code=exited, status=1/FAILURE
mag 19 12:16:17 hypernets-cnr1 systemd[1]: hypernets-hello.service: Failed with result 'exit-code'.

**Comment by javierconcha** [comment]
The prefix working. Thanks!

And the problem reported by Vittorio was solved with a git stash and a git pull.
