### ISSUE TITLE
Add way to know when rsync is complete

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_tools#50]
Hi @corizzi  - it would be really helpful in the hypernets processor to be able to tell when the data has finished transferring to the server, so we know when to begin processing. We originally opened an [issue](https://github.com/HYPERNETS/hypernets_processor/issues/144) for this in hypernets_processor, where @jkuusk made a suggestion for a fix. Thanks!

**Comment by corizzi** [comment]
Hi @shunt16 , 

As LOGS/ is synchronized after DATA/:

https://github.com/HYPERNETS/hypernets_tools/blob/93984a48698bd0ddbdd92b4e6acd2dce672c21cd/utils/hello_server.sh#L88-L91

We can also use the respective timestamps of each folder, for example:

```
dataTimeStamp=$(stat -c %Y DATA/)
logsTimeStamp=$(stat -c %Y LOGS/)

if [ "$dataTimeStamp" -lt "$logsTimeStamp" ] ; then
    echo "Sync is done!"
else
    echo "Syncing..."
```

**Comment by pdevis** [comment]
OK we can use the log files to check if data has finished syncing then. Thanks

**Comment by corizzi** [comment]
Hi @shunt16 , 

I added a line at the end of the log that must show something like:
`Created sequence : DATA/SEQYYYYDDMMTHHMMSS`

The naming of the log files are somehow offset because the date-time creation of the log is used. It is a bit confusing but a convenient choice as a "boot" does not necessary contain a sequence creation.

In any case, if you are looking for the sequence folder name according to a specific log file: _yyyy-mm-dd-sequence.log_
you can try to use the following bash code snippet:
```
f=yyyy-mm-dd-sequence.log
sequenceName=$(grep -m1 "CUR" $f)
sequenceName=$(echo "$sequenceName" | cut -d'/' -f2)
sequenceName=$(echo "SEQ${sequenceName:3}")
```
I hope it helps
